<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Find a Partner</name>
   <tag></tag>
   <elementGuidId>91f3a5b5-7f5f-42d0-9064-2f6bcc1ac670</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='partner-banner-section']/div/div[2]/a/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.btn-find-partner</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#partner-banner-section >> internal:role=link[name=&quot;Find a Partner&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8c27d30f-ad3e-4ece-a62a-4e26c2d2f3fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-find-partner</value>
      <webElementGuid>db75d204-da3e-417d-8ddd-ec623fa714dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Find a Partner</value>
      <webElementGuid>929a6e27-0510-4f16-be25-17c04be4e2d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;partner-banner-section&quot;)/div[@class=&quot;content-container&quot;]/div[@class=&quot;banner-button-section&quot;]/a[1]/div[@class=&quot;btn-find-partner&quot;]</value>
      <webElementGuid>dff046b7-0769-4bc4-8a18-032635d95a17</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='partner-banner-section']/div/div[2]/a/div</value>
      <webElementGuid>dbbd1b18-3d69-4ea3-94fd-6d093f54496a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Katalon Partner Programs'])[2]/following::div[3]</value>
      <webElementGuid>30acc566-8df1-4bd4-8295-bc5d61d8e14b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Build up your expertise in CI/CD with technical assistance from the Katalon team.'])[1]/following::div[4]</value>
      <webElementGuid>af69c6b8-dd54-412c-9e2c-30b4d6d2762a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Become a Partner'])[2]/preceding::div[1]</value>
      <webElementGuid>f5e2c7cd-5e94-4279-bf15-968b9397b4c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Why Katalon'])[1]/preceding::div[4]</value>
      <webElementGuid>6ee0bac0-2c90-40a2-80ce-06cf5482a8f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[4]/div/div[2]/a/div</value>
      <webElementGuid>1aa8d628-f1d2-4110-9777-77ea0bd347a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Find a Partner' or . = 'Find a Partner')]</value>
      <webElementGuid>2a33ff11-b7d5-4705-b00d-31d38b324d2c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
