<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Discover forum</name>
   <tag></tag>
   <elementGuidId>2ee72e9d-1df0-41b6-8e4f-5ea249e38b68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div[2]/section[2]/section[2]/div/div/div/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.Trending_btnGroup__iwiI7 > a:nth-of-type(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Discover forum&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4b5b0b62-25b6-410f-b8ec-cb75be944fe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://forum.katalon.com/</value>
      <webElementGuid>bf2bcfdd-8b93-4ffc-a485-06190554f66a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Discover forum</value>
      <webElementGuid>c0b75bbe-03e9-440a-aedf-38ec965b65f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[@class=&quot;CommunityHub_container__OZzzN&quot;]/section[@class=&quot;Trending_container__r_Ebw&quot;]/section[@class=&quot;cmContainer&quot;]/div[@class=&quot;Trending_sectionDiscussions__fixFB&quot;]/div[@class=&quot;Trending_left__tmiY7&quot;]/div[@class=&quot;Trending_btnGroup__iwiI7&quot;]/a[2]</value>
      <webElementGuid>de94b8de-4bed-4664-8d2c-42d78e62b38b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/section[2]/section[2]/div/div/div/a[2]</value>
      <webElementGuid>38b2969f-e7fb-4a8f-89d5-205a533d0a28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Discover forum')]</value>
      <webElementGuid>412a76ab-bd48-4579-9bed-8cb05fdd85d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ask a question'])[1]/following::a[1]</value>
      <webElementGuid>cb7a2935-f007-438d-9bfc-337ee0b5a7cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trending discussions'])[1]/following::a[2]</value>
      <webElementGuid>075c741e-51b3-4f62-8e5c-dfb24f5d1f69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Discover forum']/parent::*</value>
      <webElementGuid>e4deb14c-bf30-4586-9140-b60f7230c3f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://forum.katalon.com/')])[3]</value>
      <webElementGuid>3c48573a-7742-43ff-b2f2-a696864a19db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div/div/div/a[2]</value>
      <webElementGuid>9ddadabd-6a08-444a-9ac2-7c35f66a61e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://forum.katalon.com/' and (text() = 'Discover forum' or . = 'Discover forum')]</value>
      <webElementGuid>c1b8b5b3-c553-4430-9f88-edb6b6f70b85</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
