<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_OthersSalesforce TestingOthers</name>
   <tag></tag>
   <elementGuidId>feebbbe7-c3b0-4340-be0f-ef3de01a7460</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='sectionKshare']/div/ul/li[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(6)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;OthersSalesforce TestingOthers&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>088f5119-18ba-4069-8de9-f4f59d1b98b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OthersSalesforce TestingOthers</value>
      <webElementGuid>af212c5e-b45d-484d-9213-da5b9bc6c0ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sectionKshare&quot;)/div[@class=&quot;cmContainer smooth-scroll&quot;]/ul[@class=&quot;Blogs_tabs__lLQBQ&quot;]/li[6]</value>
      <webElementGuid>22895590-d019-4698-927d-7855ab5118f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='sectionKshare']/div/ul/li[6]</value>
      <webElementGuid>bf5579e9-8070-4731-bb92-0f709853eef5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='iOS Testing'])[1]/following::li[1]</value>
      <webElementGuid>30d7dcea-7236-4bdf-a845-98441499c99f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Others']/parent::*</value>
      <webElementGuid>156421bb-f38d-4b38-a789-051123dfee40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]</value>
      <webElementGuid>fa82e600-6fb7-44ce-86fd-ea386394a70b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'OthersSalesforce TestingOthers' or . = 'OthersSalesforce TestingOthers')]</value>
      <webElementGuid>cb25cbfe-cbe5-45ab-82cc-1900737c5030</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
