<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Book a call_insent-popup-card-close</name>
   <tag></tag>
   <elementGuidId>5c832910-2fd1-4d35-a63c-8f21895eb639</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='insent-popup-card-close']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#insent-popup-card-close</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#insent-popup-card-close</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>87a578d7-8de8-45a2-ab76-4b166a087ce1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>insent-popup-card-close</value>
      <webElementGuid>1c9faad0-c245-479c-a37a-d4102a7337a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-hUMlYv kdefww card-close</value>
      <webElementGuid>e64ec258-f212-403d-97d9-aaf2b5504d0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;insent-popup-card-close&quot;)</value>
      <webElementGuid>2b82acb0-5eb4-4191-a517-3cd98283ea3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Solutions/Page_Government Software Testing Solution  Katalon/iframe_concat(id(, , insent-iframe, , ))_in_d2847a</value>
      <webElementGuid>e886abbb-1f02-499d-9be4-f532faa3f408</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='insent-popup-card-close']</value>
      <webElementGuid>731bfcd7-c868-4c01-a855-4ece3eb29fb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='insent-popup-wrapper']/div[2]</value>
      <webElementGuid>6c0dac17-d322-450e-b4b5-72875d0df572</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Book a call'])[1]/following::div[1]</value>
      <webElementGuid>974b192d-bb6a-4a04-86c7-70e766e622c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ask a question'])[1]/following::div[2]</value>
      <webElementGuid>32c80f78-003a-4593-80b2-10c892948b75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]</value>
      <webElementGuid>b0fcc10e-8307-4131-877c-b1f946be9fdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'insent-popup-card-close']</value>
      <webElementGuid>61d939c8-0afd-4075-b6ef-51e210c73333</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
