<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Book a call_insent-popup-card-close</name>
   <tag></tag>
   <elementGuidId>09a4a900-a921-4847-a697-ada2c2c349e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='insent-popup-card-close']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#insent-popup-card-close</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#insent-popup-card-close</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>20bdbc9b-e262-43c5-99f2-cb9a13de710f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>insent-popup-card-close</value>
      <webElementGuid>32306ccf-a65a-4284-8aed-282fab968fa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-hUMlYv kdefww card-close</value>
      <webElementGuid>3f0b168b-7e07-4b3a-a4cf-7659ea824859</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;insent-popup-card-close&quot;)</value>
      <webElementGuid>d5ecf136-c3a3-4f51-8e24-c96723135a4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Products/Page_Katalon TestCloud  Cloud-based Test Ex_68c4d3/iframe_concat(id(, , insent-iframe, , ))_in_d2847a</value>
      <webElementGuid>f8f3f5f8-1179-4e12-b0d4-9ec8b5fa42e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='insent-popup-card-close']</value>
      <webElementGuid>16e30cfe-8833-473c-8f69-6e07f85ec7ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='insent-popup-wrapper']/div[2]</value>
      <webElementGuid>69117a46-23b0-4497-badb-3cf38c2d0d71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Book a call'])[1]/following::div[1]</value>
      <webElementGuid>14e4e4e2-97ab-498b-9ece-c660ab8ee693</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ask a question'])[1]/following::div[2]</value>
      <webElementGuid>a5a43dd4-1d4e-4d11-b2b7-8876a538e1ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]</value>
      <webElementGuid>07dfbb83-5271-45c0-a31a-8f67b2bdf065</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'insent-popup-card-close']</value>
      <webElementGuid>a7c00d68-4dc3-4226-a616-565240bbcb8d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
