<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Handle ever-changing ecosystems and bus_2b348e</name>
   <tag></tag>
   <elementGuidId>8b5edc54-d62b-4c43-a6c1-fd3b21e25f9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='out-of-the-box-integrations']/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.content > div.description</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Handle ever-changing ecosystems and business demands.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4da5b98d-5144-480c-b7c2-76db325a94bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>description</value>
      <webElementGuid>31ad767a-71f5-40df-9403-e542559f508f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Handle ever-changing ecosystems and business demands.</value>
      <webElementGuid>7869bc4a-a765-4346-a264-4d51d465d841</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;out-of-the-box-integrations&quot;)/div[@class=&quot;content&quot;]/div[@class=&quot;description&quot;]</value>
      <webElementGuid>5fec29fe-2b32-43b8-8d9c-3c45646e2b01</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='out-of-the-box-integrations']/div/div[2]</value>
      <webElementGuid>35424a54-ac15-4696-9fe8-ea286a1d2afe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Out-of-the-box integrations'])[1]/following::div[1]</value>
      <webElementGuid>afded3f7-bea1-47a9-a969-b1388916aa0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='More than 100,000+ users'])[1]/following::div[6]</value>
      <webElementGuid>d977f1fd-8910-4e2f-8879-95d9544a5afd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Various cloud-based environments'])[1]/preceding::div[1]</value>
      <webElementGuid>cd6246d8-0ef2-4617-886e-0f279f8e0c17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Provide instant access to thousands of browsers, device and OS combinations.'])[1]/preceding::div[2]</value>
      <webElementGuid>8d049191-5bb3-4660-bac1-c3134eec2f4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Handle ever-changing ecosystems and business demands.']/parent::*</value>
      <webElementGuid>982f9299-592f-45d4-9f42-76ce545e3060</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[2]/div/div/div/div[2]</value>
      <webElementGuid>e8a00176-7f48-489d-bea2-4390195ebfa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Handle ever-changing ecosystems and business demands.' or . = 'Handle ever-changing ecosystems and business demands.')]</value>
      <webElementGuid>f8b635e3-8cae-425b-b854-177e3cb86e2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
