<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Can I purchase single licenses in Premium</name>
   <tag></tag>
   <elementGuidId>aa381834-45ec-4e3f-b517-4eab175e4728</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div[2]/div[8]/div/div[3]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Can I purchase single licenses in Premium?+&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>932a3712-c23e-45d6-8ff9-8fb44c995a6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wrap_question</value>
      <webElementGuid>a028973c-88d9-4857-9403-4a345e69636e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Can I purchase single licenses in Premium?+</value>
      <webElementGuid>1ab003e2-4e8d-4452-9c11-90cebaf3f2da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[@class=&quot;Pricing_wrapPricing__WZZPj&quot;]/div[@class=&quot;FAQ-section&quot;]/div[@class=&quot;FAQ-tab&quot;]/div[@class=&quot;FAQ-item&quot;]/div[@class=&quot;wrap_question&quot;]</value>
      <webElementGuid>d22cbdc6-bf02-422f-aa4d-d0a0377d8ba0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/div[8]/div/div[3]/div</value>
      <webElementGuid>75689f2d-8fa8-4d0a-828f-4b580a729ca6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remote execution:'])[1]/following::div[2]</value>
      <webElementGuid>19c67b7b-4234-4691-98ea-3fe81358397c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test creation:'])[1]/following::div[2]</value>
      <webElementGuid>c3b8b5c8-b642-4681-bcf7-7ade9bdab82c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div[3]/div</value>
      <webElementGuid>77f463b5-f8cb-4ef9-b1df-27e9ebdb72c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Can I purchase single licenses in Premium?+' or . = 'Can I purchase single licenses in Premium?+')]</value>
      <webElementGuid>6d62d9f6-66c4-4123-840b-cb8e1f7d3c01</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
