<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>0108d6ca-7df1-409e-afae-501f6dabc66a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div[2]/div[6]/div[2]/div[2]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.view_all_feature_btn.trackable > div.icon > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.view_all_feature_btn > .icon > img</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0a696159-aee5-4e62-a5ec-77e850461b1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://d1h3p5fzmizjvp.cloudfront.net/themes/katalon_4/images/pages/pricing_apr_2024/view_all_features_icon.svg</value>
      <webElementGuid>271b5075-6943-4210-912a-9a141f1f8dd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>7574fb45-8905-45ee-977b-7760180eb2d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[@class=&quot;Pricing_wrapPricing__WZZPj&quot;]/div[@class=&quot;compare_plan_blur_wrap&quot;]/div[@class=&quot;view_all_feature_btn trackable&quot;]/div[@class=&quot;icon&quot;]/img[1]</value>
      <webElementGuid>d8a85560-8211-49c4-a197-6c16f6b40ad4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/div[6]/div[2]/div[2]/img</value>
      <webElementGuid>8c07b1be-f2d6-49b4-a480-8d4145dc4ddf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://d1h3p5fzmizjvp.cloudfront.net/themes/katalon_4/images/pages/pricing_apr_2024/view_all_features_icon.svg')]</value>
      <webElementGuid>e4ab8741-0702-407a-a218-e0ed5aac96fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div[2]/img</value>
      <webElementGuid>26d187b3-2af5-44cd-898b-37e2fe03b65a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://d1h3p5fzmizjvp.cloudfront.net/themes/katalon_4/images/pages/pricing_apr_2024/view_all_features_icon.svg']</value>
      <webElementGuid>debe0b02-bad4-47bc-9b2d-900c10f9452f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
