<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Browse all jobs_btn_scroll_next</name>
   <tag></tag>
   <elementGuidId>9f9bae35-5407-4b3f-96b9-083cb4999b9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div[2]/section[3]/div[4]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.btn_scroll_next</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.btn_scroll_next</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>88d9987c-bfbe-4689-9d31-0ec994c213c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn_scroll_next</value>
      <webElementGuid>f9957967-ee7f-4233-8c20-a0b422482b67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[@class=&quot;HomePage_wrapHomePage__zdHwS&quot;]/section[@class=&quot;recruitment_spotlight_section&quot;]/div[@class=&quot;scroll_button&quot;]/div[@class=&quot;btn_scroll_next&quot;]</value>
      <webElementGuid>a7b7e6e4-fb97-4afd-889f-89f855a44973</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/section[3]/div[4]/div[2]</value>
      <webElementGuid>d4feba9c-e678-4e72-8496-88766dcbdb85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Browse all jobs'])[1]/following::div[4]</value>
      <webElementGuid>498e2d58-da8d-4ffa-9cb8-f4a28153bbfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Malaysia'])[1]/following::div[7]</value>
      <webElementGuid>e5d7af71-609c-4630-86e2-b5166cc9ca59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Remuneration'])[1]/preceding::div[4]</value>
      <webElementGuid>de7f97de-f912-400f-a350-4473baa9c128</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]</value>
      <webElementGuid>aff0df6a-a24b-483e-a3a8-dbf1e4477638</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
