<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Katalon Platform</name>
   <tag></tag>
   <elementGuidId>3441a0df-2fb6-4f1c-987b-5518c85c5cc9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__docusaurus_skipToContent_fallback']/div/main/section/div/div/a/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.buttonTitle_y9wb</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Katalon Platform Collaborate and scale your testing workflow with our dynamic quality management platform&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>911ef9d8-b23b-48cd-ae9e-d872e021c3b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>buttonTitle_y9wb</value>
      <webElementGuid>f50608c1-426a-4874-b434-6779e02556af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Katalon Platform</value>
      <webElementGuid>c4c96ecf-6095-479d-9b07-f4caa7f6c696</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__docusaurus_skipToContent_fallback&quot;)/div[@class=&quot;container_mm4O&quot;]/main[1]/section[1]/div[@class=&quot;container container_jny4&quot;]/div[@class=&quot;buttons_mH_C&quot;]/a[@class=&quot;button_JiHK buttonPlatform_m5Dt&quot;]/div[@class=&quot;buttonTitle_y9wb&quot;]</value>
      <webElementGuid>062bc04d-34cd-4ece-8c99-26ce65063d56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__docusaurus_skipToContent_fallback']/div/main/section/div/div/a/div[2]</value>
      <webElementGuid>2d1ddb90-5b24-4ce0-81e3-d76a6a546429</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Katalon docs'])[1]/following::div[11]</value>
      <webElementGuid>d8f90a64-8e95-45c7-9d4d-8ccb3502c94d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start now'])[1]/following::div[15]</value>
      <webElementGuid>a00335ea-9da9-4fe0-8ec8-01dc2beef704</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Collaborate and scale your testing workflow with our dynamic quality management platform'])[1]/preceding::div[1]</value>
      <webElementGuid>a86f2960-d4c3-4a2d-b8ac-f67f68803261</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Katalon Studio'])[2]/preceding::div[3]</value>
      <webElementGuid>3e1718c3-281c-45f3-9bfb-5d87a7bd953c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div[2]</value>
      <webElementGuid>b5865570-d8e0-482a-91b0-372a33d0a69c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Katalon Platform' or . = 'Katalon Platform')]</value>
      <webElementGuid>d12245bf-03bd-41d5-827d-48804d90bd21</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
